# Generated by Django 4.0.5 on 2022-07-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizApp_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quiz_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizApp_quiz',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizapp.quizapp_category')),
            ],
        ),
        migrations.CreateModel(
            name='QuizApp_question',
            fields=[
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizapp.quizapp_quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizApp_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(max_length=400)),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizapp.quizapp_question')),
            ],
        ),
    ]
