# Generated by Django 4.0.5 on 2022-07-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizapp_category',
            name='quiz_count',
        ),
    ]
